### PR TITLE
Storing ingredients in db

### PR DESCRIPTION
**Pull request by kowodo**

### CODE REVIEW

**Comment by petrmvala** [comment]
It seems to me, that the problem happens during tests. The github action we have there is just compiling the sources and running the tests. I tried it on my local also, even split:
`mvn compile -f foodshopper/pom.xml` --> works fine regardless on whether the DB is up
`mvn test -f foodshopper/pom.xml` --> runs fine when DB is up, but fails when it isn't

**Comment by petrmvala** [comment]
I tried re-executing the clean build after you merged main into your branch, but the tests are still failing on trying to connect to the DB:
https://github.com/petrmvala/foodshopper/runs/2143631396?check_suite_focus=true#step:4:1189

**Comment by kowodo** [comment]
> I tried re-executing the clean build after you merged main into your branch, but the tests are still failing on trying to connect to the DB:
> https://github.com/petrmvala/foodshopper/runs/2143631396?check_suite_focus=true#step:4:1189

Thanks for checking it out!
The latest commit should address the issue. 
Two profiles were created, development and production.
the development profile is connecting to in-memory db,
the production is connecting to postgres.

**Review by petrmvala — APPROVED** [review]
Great work! Thank you!

**Pull request merged**
